# Covariance and Correlation

In [14]:
import seaborn as sns

In [15]:
df = sns.load_dataset('healthexp')
df.head()

   Year        Country  Spending_USD  Life_Expectancy
0  1970        Germany       252.311             70.6
1  1970         France       192.143             72.2
2  1970  Great Britain       123.993             71.9
3  1970          Japan       150.437             72.0
4  1970            USA       326.961             70.9

In [16]:
df_cov = df.select_dtypes(include=['number'])
df_cov.cov()

                         Year  Spending_USD  Life_Expectancy
Year               201.098848  2.571883e+04        41.915454
Spending_USD     25718.827373  4.817761e+06      4166.800912
Life_Expectancy     41.915454  4.166801e+03        10.733902

In [17]:
# Pearson correlation coefficient
df_corr_prsn = df.select_dtypes(include=['number'])
df_corr_prsn.corr(method='pearson')

                     Year  Spending_USD  Life_Expectancy
Year             1.000000      0.826273         0.902175
Spending_USD     0.826273      1.000000         0.579430
Life_Expectancy  0.902175      0.579430         1.000000

In [18]:
## spearman rank correlation
df_corr_sprn = df.select_dtypes(include=['number'])
df_corr_sprn.corr(method='spearman')

                     Year  Spending_USD  Life_Expectancy
Year             1.000000      0.931598         0.896117
Spending_USD     0.931598      1.000000         0.747407
Life_Expectancy  0.896117      0.747407         1.000000

## flights DATASET

In [23]:
df0 = sns.load_dataset('flights')
df0.head()

   year month  passengers
0  1949   Jan         112
1  1949   Feb         118
2  1949   Mar         132
3  1949   Apr         129
4  1949   May         121

In [25]:
df_cov0 = df0.select_dtypes(include=['number'])
df_cov0.cov()

                  year    passengers
year         12.000000    383.087413
passengers  383.087413  14391.917201

## tips DATASET

In [26]:
df1 = sns.load_dataset('tips')
df1.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [27]:
df_cov1 = df1.select_dtypes(include=['number'])
df_cov1.cov()

            total_bill       tip      size
total_bill   79.252939  8.323502  5.065983
tip           8.323502  1.914455  0.643906
size          5.065983  0.643906  0.904591